approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - yatil
  - nitedog
  - susanatx
  - haltersweb
  - dboudreau
  - hkramer
  name: default
  required: 2
